# App labels
frontend:
  - changed-files:
    - any-glob-to-any-file: 'apps/excelidraw-frontend/**/*'

web:
  - changed-files:
    - any-glob-to-any-file: 'apps/web/**/*'

http-backend:
  - changed-files:
    - any-glob-to-any-file: 'apps/http-backend/**/*'

ws-backend:
  - changed-files:
    - any-glob-to-any-file: 'apps/ws-backend/**/*'

# Package labels
packages:
  - changed-files:
    - any-glob-to-any-file: 'packages/**/*'

db:
  - changed-files:
    - any-glob-to-any-file: 'packages/db/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file: 'packages/ui/**/*'

# CI/CD labels
ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
    - any-glob-to-any-file: 'turbo.json'
