blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & Support
    url: https://github.com/rajputdivyanshu81/QuickDraw/discussions/new?category=q-a
    about: Please ask questions and get support in our GitHub Discussions.
